<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_header_Newsletter</name>
   <tag></tag>
   <elementGuidId>9557acb9-7ec8-424c-a3b2-0b82dadad3f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>strong</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//aside[@id='text-5']/div/h3/strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>d59823a9-f58a-4b57-8f48-fb9462b053ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Newsletter
</value>
      <webElementGuid>47aa8b1f-4b00-4007-b72a-653ad91d07ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text-5&quot;)/div[@class=&quot;textwidget&quot;]/h3[1]/strong[1]</value>
      <webElementGuid>7fb05687-20fd-4673-84de-6a3ecae523d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//aside[@id='text-5']/div/h3/strong</value>
      <webElementGuid>5ebecad5-7e68-4e46-9e67-b0a7c544784a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to cart'])[7]/following::strong[1]</value>
      <webElementGuid>2aa5c597-4333-4959-a56a-76f896ac2f11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quick View'])[7]/following::strong[1]</value>
      <webElementGuid>96dde009-ae7a-45f0-ba03-5e26b5daa29d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/preceding::strong[1]</value>
      <webElementGuid>99cc0020-f5ce-45e2-82e8-cb0a3eaecda9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Newsletter']/parent::*</value>
      <webElementGuid>f3dc23ad-c417-459d-9e6b-a7515733e690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//strong</value>
      <webElementGuid>11e05bd4-c08e-40de-9a00-be242400c963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = 'Newsletter
' or . = 'Newsletter
')]</value>
      <webElementGuid>e94af7c0-3477-4ff1-b71d-de6cb7734f69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
