<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>close_alert_Password is incorrect (top of username)</name>
   <tag></tag>
   <elementGuidId>55b7c5d4-71fe-4711-8582-26db7f4a4e42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//i[@onclick='jQuery(this).parent().fadeOut();']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.um-icon-ios-close-empty</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>147ae79d-4c7a-4d59-9071-4dc6fc697089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>um-icon-ios-close-empty</value>
      <webElementGuid>55f7e38d-097f-4fe9-8c60-74b834d4af40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>jQuery(this).parent().fadeOut();</value>
      <webElementGuid>d88bfa42-6dcd-45a8-bb2c-9d5bc0af8065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-313&quot;)/div[@class=&quot;entry-content&quot;]/div[@class=&quot;um um-login um-err um-298 uimob500&quot;]/div[@class=&quot;um-form&quot;]/form[1]/p[@class=&quot;um-notice err um-error-code-invalid_username&quot;]/i[@class=&quot;um-icon-ios-close-empty&quot;]</value>
      <webElementGuid>cc387e30-032b-4290-8953-3e85aeb8c471</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@onclick='jQuery(this).parent().fadeOut();']</value>
      <webElementGuid>fc943752-2889-426a-a3b3-a8d1ac969e76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-313']/div/div/div/form/p/i</value>
      <webElementGuid>af340930-f91a-4bc3-b758-7c4098e5e1db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/i</value>
      <webElementGuid>f52b4ff6-a12c-4da4-a425-c6106d171262</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
