<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_alert_Password is incorrect. Please try again</name>
   <tag></tag>
   <elementGuidId>de3816ed-165e-4754-983c-a98069505a42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='um_field_298_user_password']/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.um-field-error</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cc39f5ab-8afa-49c3-bbe9-eab3579634b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>um-field-error</value>
      <webElementGuid>5c8a0667-a093-4cee-9ff7-16b80889a99a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Password is incorrect. Please try again.</value>
      <webElementGuid>05f22152-61de-4471-ac55-4be3215ca311</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;um_field_298_user_password&quot;)/div[@class=&quot;um-field-error&quot;]</value>
      <webElementGuid>e71a90b8-9222-423e-bf30-dff29cf07333</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='um_field_298_user_password']/div[3]</value>
      <webElementGuid>d2f71ed6-1adf-4463-8da9-04c4befddad7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::div[3]</value>
      <webElementGuid>9c9dc1d2-5f65-47bd-b995-0dcbf58e6f49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username or E-mail'])[1]/following::div[7]</value>
      <webElementGuid>e03746c8-3a47-4eba-8662-49b821816a91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Only fill in if you are not human'])[1]/preceding::div[1]</value>
      <webElementGuid>e990f02b-dd69-47a4-83a1-bd6864d117eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keep me signed in'])[1]/preceding::div[1]</value>
      <webElementGuid>2e512cd0-be8a-4dbf-add7-5e200d256cd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div[3]</value>
      <webElementGuid>b23f4146-9e5e-4491-afce-54f60ce38647</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Password is incorrect. Please try again.' or . = 'Password is incorrect. Please try again.')]</value>
      <webElementGuid>ef319caa-0055-4790-a9f1-268ac3817647</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
