<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_text_Email</name>
   <tag></tag>
   <elementGuidId>7cdabcfa-cfe5-46db-9cb4-97ba4f2a8a8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#user_email-297</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='user_email-297']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5d3df8bb-9418-4123-bedc-95d947d439ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5cf90447-1446-427a-a51a-5f021a1b8ba5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>um-form-field valid </value>
      <webElementGuid>52567823-6535-4d04-92c5-2d625ac2b9de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>16220276-46bd-4468-893e-4e0c9e0998df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user_email-297</value>
      <webElementGuid>4cd1127c-5f45-43e3-8c99-8427377e3629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user_email-297</value>
      <webElementGuid>bcef3707-5764-419c-b4f5-3988c3c2c338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validate</name>
      <type>Main</type>
      <value>unique_email</value>
      <webElementGuid>4b08e9ca-24ff-46fb-948f-79ccf429114b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>user_email</value>
      <webElementGuid>508c107e-8982-438a-8f79-d4c78f009097</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_email-297&quot;)</value>
      <webElementGuid>e3950975-a072-4128-9edf-d0d70e0eded2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='user_email-297']</value>
      <webElementGuid>c9de9c54-4a15-4bce-8be2-a92cd3fb5aaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='um_field_297_user_email']/div[2]/input</value>
      <webElementGuid>54f8a6aa-0b9c-4b1d-aa26-be27cc634058</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>78f013ed-714c-49b8-96b0-d6d7a9e67ac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'user_email-297' and @id = 'user_email-297']</value>
      <webElementGuid>2780363b-e7c3-43f0-9d02-e6a17f100ce7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
