<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_alert_Username is required</name>
   <tag></tag>
   <elementGuidId>88b17b6d-70d0-4743-a805-cbdcb17c3ea5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.um-field-error</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='um_field_297_user_login']/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f0e6970e-78cf-49d6-a023-4ee6aeab62ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>um-field-error</value>
      <webElementGuid>8a1c5425-9292-4eb2-b5ee-48f024a6d582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Username is required</value>
      <webElementGuid>5d657102-0b68-400d-9c01-e95c8673184a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;um_field_297_user_login&quot;)/div[@class=&quot;um-field-error&quot;]</value>
      <webElementGuid>6406b79d-89c3-4dfc-be38-4712bd3a946b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='um_field_297_user_login']/div[3]</value>
      <webElementGuid>3a3fbc88-615d-48eb-a26c-e10eb99938ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username'])[1]/following::div[3]</value>
      <webElementGuid>5219bdc7-4f53-4c41-bd37-f35b5c0a6810</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register Now'])[4]/following::div[10]</value>
      <webElementGuid>c8098ab4-0ba5-4167-a6f9-e4f2c854b21f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E-mail Address'])[1]/preceding::div[1]</value>
      <webElementGuid>bd1aab83-33b0-4686-8a6b-c425a7e59a98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You must provide your email'])[1]/preceding::div[4]</value>
      <webElementGuid>02f5ca4b-3590-4882-a15a-76cf35866b93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Username is required']/parent::*</value>
      <webElementGuid>f3cc2703-9ccc-4425-be2e-571daa4db666</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div/form/div/div/div/div[3]</value>
      <webElementGuid>962bcde0-8a20-4ebf-957d-2f51777db976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Username is required' or . = 'Username is required')]</value>
      <webElementGuid>eb0cf34b-24c5-497b-b2f1-d1963e4edc57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
