<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_alert_You must provide your email</name>
   <tag></tag>
   <elementGuidId>46bb4cfa-43e3-41ba-bd3a-7bcca04f0ced</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#um_field_297_user_email > div.um-field-error</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='um_field_297_user_email']/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>98243d96-36d0-45a2-a984-0cea9e70e270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>um-field-error</value>
      <webElementGuid>7988eec4-d6eb-4ab4-8ac5-f763e1f27860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>You must provide your email</value>
      <webElementGuid>864d32df-5ef1-42f2-bdb2-dbc9576fd122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;um_field_297_user_email&quot;)/div[@class=&quot;um-field-error&quot;]</value>
      <webElementGuid>9a169ff2-ab05-44a5-adb6-bfaa4d02b634</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='um_field_297_user_email']/div[3]</value>
      <webElementGuid>a09a2066-80f4-4dae-a9b9-23fafd6bdebb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E-mail Address'])[1]/following::div[3]</value>
      <webElementGuid>05d0d822-6e03-496b-b2e2-11124019d3e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username is required'])[1]/following::div[5]</value>
      <webElementGuid>841cbf7d-b845-4b9e-a359-e30ededa0dd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone Number'])[1]/preceding::div[1]</value>
      <webElementGuid>1faf8e2e-2a89-44c8-b66b-00a98c094760</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/preceding::div[5]</value>
      <webElementGuid>fe0a4ece-f95a-420f-a55c-3f8938acaae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='You must provide your email']/parent::*</value>
      <webElementGuid>a133026a-05a5-4118-94b2-bcf98a60123c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]</value>
      <webElementGuid>af4c5e69-1712-42da-9345-cd85c8f38dc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'You must provide your email' or . = 'You must provide your email')]</value>
      <webElementGuid>afbec779-eb50-4bf9-a57d-dc2f4884df58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
