<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Cart_minicart_infos</name>
   <tag></tag>
   <elementGuidId>c9719b17-3e91-44fb-9012-814133fd3ef8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.minicart_infos</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header-normal-minicart']/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>710f7958-76f8-407c-b78a-3089268ea91c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>minicart_infos</value>
      <webElementGuid>892ce194-74d3-4e62-be6d-5370493b5b77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-normal-minicart&quot;)/div[@class=&quot;minicart_infos&quot;]</value>
      <webElementGuid>ee631721-a671-4489-9d00-6d5171d27e01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header-normal-minicart']/div[2]</value>
      <webElementGuid>c22b277b-61b5-4f29-abdb-4b8d2b87617b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/div[2]</value>
      <webElementGuid>fc2cf4d7-5343-41d8-8911-c1f34a71f829</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
