<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>anchor_PIPILTIN COCOA</name>
   <tag></tag>
   <elementGuidId>694f37d7-d1f1-4084-9423-b7a2ae4d9ebd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.cat-item.cat-item-82 > a.site-secondary-font</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/div/div/div/aside/aside/ul/li[8]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>db0e8a14-8ddb-429a-8daf-1e543d4d4275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>site-secondary-font</value>
      <webElementGuid>b12851e2-6f00-4631-97ba-0bb05646b771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://kotakoki.wijaysali.my.id/product-category/pipiltin-cocoa/</value>
      <webElementGuid>fce0a0af-e3d2-4e8c-bbea-6e5b32b993f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PIPILTIN COCOA</value>
      <webElementGuid>de2121db-9c73-496b-9843-08e09163ced9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;small-12 large-3 columns show-for-large&quot;]/div[@class=&quot;woocommerce-sidebar-sticky&quot;]/aside[@class=&quot;site-sidebar site-sidebar--shop widget-area&quot;]/aside[@class=&quot;widget woocommerce widget_product_categories_with_icon&quot;]/ul[@class=&quot;product-categories-with-icon&quot;]/li[@class=&quot;cat-item cat-item-82&quot;]/a[@class=&quot;site-secondary-font&quot;]</value>
      <webElementGuid>712c7be0-4aa1-4402-8fb6-ec679d6fa8e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div/div/aside/aside/ul/li[8]/a</value>
      <webElementGuid>5e90ec09-564d-4e52-a108-1afbfc027c46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'PIPILTIN COCOA')]</value>
      <webElementGuid>8cab4f8c-2720-449a-a9d2-0df27fccaf93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KOTAKOKI SET'])[2]/following::a[1]</value>
      <webElementGuid>23d2cc73-1244-4f06-9c10-3d044c2ecec3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HOME PAGE'])[2]/following::a[2]</value>
      <webElementGuid>305d7b0f-d406-438d-bdb2-940ac02e4ea9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='READY TO EAT'])[2]/preceding::a[1]</value>
      <webElementGuid>9be019c8-9a90-4c20-8211-eed359a27438</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SEAFOOD'])[2]/preceding::a[2]</value>
      <webElementGuid>5906c254-6ede-4a5a-ad18-9b788fa329f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://kotakoki.wijaysali.my.id/product-category/pipiltin-cocoa/']</value>
      <webElementGuid>0a22697e-777b-4d18-9550-a5c224286e3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/a</value>
      <webElementGuid>70c83db0-a72f-416f-9b30-591cc43967e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://kotakoki.wijaysali.my.id/product-category/pipiltin-cocoa/' and (text() = 'PIPILTIN COCOA' or . = 'PIPILTIN COCOA')]</value>
      <webElementGuid>49f35829-8c0e-47a9-86e1-dbbbe93b0126</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
