<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>anchor_SPICES</name>
   <tag></tag>
   <elementGuidId>6091e19b-2b43-454d-af7b-32382a7a2854</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.cat-item.cat-item-79 > a.site-secondary-font</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/div/div/div/aside/aside/ul/li[11]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fa72c08d-6fb8-4e4a-8dc5-0a83ce0b754a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>site-secondary-font</value>
      <webElementGuid>25db1208-f1c3-401e-8cd7-2fa8b68c2a1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://kotakoki.wijaysali.my.id/product-category/spices/</value>
      <webElementGuid>1570da00-7520-492d-928c-62647b456e3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SPICES</value>
      <webElementGuid>5a7848ae-f719-4c91-a5a7-2488d6f1b5c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;small-12 large-3 columns show-for-large&quot;]/div[@class=&quot;woocommerce-sidebar-sticky&quot;]/aside[@class=&quot;site-sidebar site-sidebar--shop widget-area&quot;]/aside[@class=&quot;widget woocommerce widget_product_categories_with_icon&quot;]/ul[@class=&quot;product-categories-with-icon&quot;]/li[@class=&quot;cat-item cat-item-79&quot;]/a[@class=&quot;site-secondary-font&quot;]</value>
      <webElementGuid>3d4d5940-000b-47c0-8f31-1c833ce74896</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div/div/aside/aside/ul/li[11]/a</value>
      <webElementGuid>31b0e3c1-dad3-4837-954a-3813f09debf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'SPICES')]</value>
      <webElementGuid>2592f175-afa0-45b3-b6bd-855fe07c2be2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SEAFOOD'])[2]/following::a[1]</value>
      <webElementGuid>32775597-318b-4505-bdf5-1b65ee8c0312</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='READY TO EAT'])[2]/following::a[2]</value>
      <webElementGuid>ec2f802f-ba5e-48f2-a4cf-94ded11e2408</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='STARTER SET'])[2]/preceding::a[1]</value>
      <webElementGuid>f9b72e7c-6d33-446b-ba26-719503f1760a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='スパイスブレンド'])[2]/preceding::a[2]</value>
      <webElementGuid>17cb54c8-fed8-4878-ba4c-1a7e04b19db2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://kotakoki.wijaysali.my.id/product-category/spices/']</value>
      <webElementGuid>73b087ed-ec09-4954-900b-acd02bc8778a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[11]/a</value>
      <webElementGuid>cc7451ec-9092-4dfb-ae70-aad2d624857b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://kotakoki.wijaysali.my.id/product-category/spices/' and (text() = 'SPICES' or . = 'SPICES')]</value>
      <webElementGuid>6cca9491-1d13-49d3-bf45-fb782d86d119</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
