<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>anchor_ (2)</name>
   <tag></tag>
   <elementGuidId>93be8adc-f41e-407c-9e53-1786e7f4316e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.cat-item.cat-item-87 > a.site-secondary-font</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/div/div/div/aside/aside/ul/li[15]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7b4dea45-8224-4ab6-ba5a-d6fc01704633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>site-secondary-font</value>
      <webElementGuid>0c6a09fd-334b-417c-adc4-52c5768929c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://kotakoki.wijaysali.my.id/product-category/%e6%96%b0%e3%81%97%e3%81%84%e3%83%ac%e3%82%b7%e3%83%94%e3%82%bb%e3%83%83%e3%83%88/</value>
      <webElementGuid>f91a6a1f-c212-4f59-9918-912ad1fcdea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>新しいレシピセット</value>
      <webElementGuid>9bed6ae2-0210-4daf-a682-3f4e888079af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;small-12 large-3 columns show-for-large&quot;]/div[@class=&quot;woocommerce-sidebar-sticky&quot;]/aside[@class=&quot;site-sidebar site-sidebar--shop widget-area&quot;]/aside[@class=&quot;widget woocommerce widget_product_categories_with_icon&quot;]/ul[@class=&quot;product-categories-with-icon&quot;]/li[@class=&quot;cat-item cat-item-87&quot;]/a[@class=&quot;site-secondary-font&quot;]</value>
      <webElementGuid>82b4186b-4c14-4cbb-82a2-5153ff5cc218</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div/div/aside/aside/ul/li[15]/a</value>
      <webElementGuid>aa17b305-e4c5-42aa-b744-401ed7da4b51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'新しいレシピセット')]</value>
      <webElementGuid>4b12aeb9-5416-4933-85ab-731d4d5c36cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='テンペ'])[2]/following::a[1]</value>
      <webElementGuid>65e6b346-7879-4e6b-9846-d5f2941c20e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='スパイスブレンド'])[2]/following::a[2]</value>
      <webElementGuid>e9140960-aa15-48a1-8761-23c572682479</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filters'])[1]/preceding::a[1]</value>
      <webElementGuid>2b275c45-e42b-4c91-88a9-1d5e0cc71732</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://kotakoki.wijaysali.my.id/product-category/%e6%96%b0%e3%81%97%e3%81%84%e3%83%ac%e3%82%b7%e3%83%94%e3%82%bb%e3%83%83%e3%83%88/']</value>
      <webElementGuid>7bae2ec3-e293-4743-a144-20201b5ec598</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[15]/a</value>
      <webElementGuid>bba9cb61-e372-421d-b16d-78dc1797dd09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://kotakoki.wijaysali.my.id/product-category/%e6%96%b0%e3%81%97%e3%81%84%e3%83%ac%e3%82%b7%e3%83%94%e3%82%bb%e3%83%83%e3%83%88/' and (text() = '新しいレシピセット' or . = '新しいレシピセット')]</value>
      <webElementGuid>5a27c8f1-1470-4278-90c1-d3d0bd6490e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
