<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>anchor_Du-reamy</name>
   <tag></tag>
   <elementGuidId>23ab0cc6-e03b-4ad8-9453-dbab1a9de61a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.cat-item.cat-item-85 > a.site-secondary-font</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/div/div/div/aside/aside/ul/li[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>362e94fc-240d-4f01-b27f-96decd16ade8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>site-secondary-font</value>
      <webElementGuid>48c9d22a-955e-46ae-ba85-42f929cf6b2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://kotakoki.wijaysali.my.id/product-category/du-reamy%e3%83%89%e3%83%aa%e3%82%a2%e3%83%b3/</value>
      <webElementGuid>59b1d98e-e691-48f3-a7e7-c31c3d27ac35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Du-reamyドリアン</value>
      <webElementGuid>0bb67de8-4a87-4955-a018-5c483f0d911b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;small-12 large-3 columns show-for-large&quot;]/div[@class=&quot;woocommerce-sidebar-sticky&quot;]/aside[@class=&quot;site-sidebar site-sidebar--shop widget-area&quot;]/aside[@class=&quot;widget woocommerce widget_product_categories_with_icon&quot;]/ul[@class=&quot;product-categories-with-icon&quot;]/li[@class=&quot;cat-item cat-item-85&quot;]/a[@class=&quot;site-secondary-font&quot;]</value>
      <webElementGuid>6948e406-68d0-44ff-8f2c-a23f1f77044e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div/div/aside/aside/ul/li[5]/a</value>
      <webElementGuid>183b6667-02f0-4f74-b479-2966a33d121d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Du-reamyドリアン')]</value>
      <webElementGuid>fea13eab-0a42-43b0-bae0-ddb0e9ac2c23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cocoqua ココナッツ'])[2]/following::a[1]</value>
      <webElementGuid>30451ed1-473a-41a4-a05f-419813ceab17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Uncategorized'])[2]/following::a[2]</value>
      <webElementGuid>01dcf1f0-2cec-49af-af05-d30fe2ef83cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HOME PAGE'])[2]/preceding::a[1]</value>
      <webElementGuid>aeffae5c-d770-453c-99f0-e4723acf8a4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KOTAKOKI SET'])[2]/preceding::a[2]</value>
      <webElementGuid>a0f93255-d0cc-40ad-86a8-0854ee85993a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://kotakoki.wijaysali.my.id/product-category/du-reamy%e3%83%89%e3%83%aa%e3%82%a2%e3%83%b3/']</value>
      <webElementGuid>8957e1fc-f6c9-45be-aa8c-f8c71e5510a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//aside/ul/li[5]/a</value>
      <webElementGuid>0e2ec054-6e3b-43f3-b823-b9d5ee7fcfe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://kotakoki.wijaysali.my.id/product-category/du-reamy%e3%83%89%e3%83%aa%e3%82%a2%e3%83%b3/' and (text() = 'Du-reamyドリアン' or . = 'Du-reamyドリアン')]</value>
      <webElementGuid>debfaae9-0ddb-4880-bc3d-acab098b8509</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
