<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_radio_LinkAja</name>
   <tag></tag>
   <elementGuidId>2b0bd432-8b72-42d4-99fe-85d97361509b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='payment_method_xendit_linkaja']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#payment_method_xendit_linkaja</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a6eed062-165c-45c9-8c61-b36ee9b16f92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payment_method_xendit_linkaja</value>
      <webElementGuid>9ecf72c8-39f1-4783-a7df-076b89de0ae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>4b9d6af5-5f8d-4cb5-b260-6ee92dda6ce1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-radio</value>
      <webElementGuid>c6ad99e6-13c8-4f46-962d-db4cac524d93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payment_method</value>
      <webElementGuid>7837ec17-6639-48e1-ab13-454522bca1d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>xendit_linkaja</value>
      <webElementGuid>2c6e0a13-b3c1-4301-aa9a-c12d94436c75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>64d8242a-c0d0-42f2-a500-8b33bb2825f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment_method_xendit_linkaja&quot;)</value>
      <webElementGuid>19d34d2d-af29-4671-b899-79d60493d8fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='payment_method_xendit_linkaja']</value>
      <webElementGuid>a41c15a4-707f-40d3-97bf-85c5b0cff5a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment']/ul/li[13]/input</value>
      <webElementGuid>957f6eb5-52b9-4760-80c5-3d8d18772608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[13]/input</value>
      <webElementGuid>25bdda63-a6cb-402e-8476-6dc626583226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'payment_method_xendit_linkaja' and @type = 'radio' and @name = 'payment_method' and @checked = 'checked']</value>
      <webElementGuid>105b88c3-20da-4c53-b20c-a143e83ab50f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
