<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_radio_PERMATAVA</name>
   <tag></tag>
   <elementGuidId>f7affbb7-7d02-477b-a8fc-1c142d6e73b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='payment_method_xendit_permatava']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#payment_method_xendit_permatava</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>16281272-8f72-4e33-98f8-c36d1b9e886b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payment_method_xendit_permatava</value>
      <webElementGuid>dcd59e86-f0bf-4305-95de-654e3c3f5e53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>9a209901-31e1-40a6-98bf-6f7cf3e75cef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-radio</value>
      <webElementGuid>0f47ce97-827d-4f15-ae76-94e2ef0c1633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payment_method</value>
      <webElementGuid>130a3ffb-21ab-49a9-991f-370ad57e99b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>xendit_permatava</value>
      <webElementGuid>2468240e-ef30-4fec-a617-946003b5747d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>8fc197d9-6a8f-4b1d-b26b-88d281a72bb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment_method_xendit_permatava&quot;)</value>
      <webElementGuid>38b1a7eb-76f5-4ea7-bc0f-a152ed3e71e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='payment_method_xendit_permatava']</value>
      <webElementGuid>a5b83fbd-a59e-462f-b276-57971be636af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment']/ul/li[7]/input</value>
      <webElementGuid>18122e4e-daff-444b-83f9-400d286891f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/input</value>
      <webElementGuid>a4c2b23a-5284-484e-bf80-e9fd62d2f05e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'payment_method_xendit_permatava' and @type = 'radio' and @name = 'payment_method' and @checked = 'checked']</value>
      <webElementGuid>e5534236-b310-4752-880c-3aefba8b38f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
