<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_total</name>
   <tag></tag>
   <elementGuidId>ebf9d91f-89ac-4c45-86c7-9f3f627e500d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='order_review']/table/tfoot/tr[2]/td/strong/span/bdi</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>strong > span.woocommerce-Price-amount.amount > bdi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>bdi</value>
      <webElementGuid>f4e832e1-1c8d-48a9-8ac1-aa511765ff6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rp30.090</value>
      <webElementGuid>99d78dfa-9ad8-4422-ac43-d5dff74fb5de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;order_review&quot;)/table[@class=&quot;shop_table woocommerce-checkout-review-order-table&quot;]/tfoot[1]/tr[@class=&quot;order-total&quot;]/td[1]/strong[1]/span[@class=&quot;woocommerce-Price-amount amount&quot;]/bdi[1]</value>
      <webElementGuid>79287320-033b-4801-ba8e-f542cd379ea9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='order_review']/table/tfoot/tr[2]/td/strong/span/bdi</value>
      <webElementGuid>4c201c3f-6447-4701-a14f-83fa01527cbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[1]/following::bdi[1]</value>
      <webElementGuid>99ff4aa6-0dec-4d7c-a7dd-787ed1a4a6e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp'])[6]/following::bdi[1]</value>
      <webElementGuid>54962aa0-5690-412f-a7ea-316ed168a50c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bank Transfer - BCA'])[1]/preceding::bdi[1]</value>
      <webElementGuid>9590ea4d-7695-4d65-acde-9fb81400ca72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//strong/span/bdi</value>
      <webElementGuid>3cd5973b-1df4-4f43-96c2-3d2c94c02e87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//bdi[(text() = 'Rp30.090' or . = 'Rp30.090')]</value>
      <webElementGuid>2963e123-b21c-46e0-aea2-083fc1290e03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
