<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_Qty_item2</name>
   <tag></tag>
   <elementGuidId>2d13ec1c-fd58-4adc-a54c-275188942fd3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='order_review']/table/tbody/tr[2]/td/strong</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>d01ff2ca-0944-45a8-bb67-800e2d69c9a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-quantity</value>
      <webElementGuid>dd24db78-4fc1-40db-b017-50f0b79a85bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>× 5</value>
      <webElementGuid>3a7fd381-4f0c-4658-8157-0e40880855a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;order_review&quot;)/table[@class=&quot;shop_table woocommerce-checkout-review-order-table&quot;]/tbody[1]/tr[@class=&quot;cart_item&quot;]/td[@class=&quot;product-name&quot;]/strong[@class=&quot;product-quantity&quot;]</value>
      <webElementGuid>bd075cce-b18d-4312-8c4c-2f8531459eac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='order_review']/table/tbody/tr[2]/td/strong</value>
      <webElementGuid>2617d7f8-1683-43e9-b52a-8ee267053488</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp'])[4]/following::strong[1]</value>
      <webElementGuid>1d9ee2db-2ca3-4add-9fc9-8969a2b5edc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp'])[5]/preceding::strong[1]</value>
      <webElementGuid>e99ac999-6f65-482b-9b71-10a3a326f5a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subtotal'])[2]/preceding::strong[1]</value>
      <webElementGuid>0adc5b08-e77a-490a-9b25-a4998ebd6dd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='× 5']/parent::*</value>
      <webElementGuid>11c40fe3-d158-48a5-bd8c-d8e22b962796</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/strong</value>
      <webElementGuid>645578d0-6282-41b4-9f2f-50b36eed34cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = '× 5' or . = '× 5')]</value>
      <webElementGuid>4a4fbcf0-c25e-4117-bf6f-2b14e707418d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
