<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_alert_Billing Postcode  ZIP is a required field</name>
   <tag></tag>
   <elementGuidId>374939ab-aa3c-4ff6-9bc3-7a98c2d1360a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-54']/div/div/form[2]/div/ul/li/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.no-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>4ffd4b2f-cf87-4cec-8994-06d514f67f3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>no-button</value>
      <webElementGuid>718cfaee-9a62-4ebf-bc5e-bad732a2868b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Billing Postcode / ZIP is a required field.</value>
      <webElementGuid>9bfd4e69-6e30-4f83-93b7-6c101f482cde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-54&quot;)/div[@class=&quot;entry-content&quot;]/div[@class=&quot;woocommerce&quot;]/form[@class=&quot;checkout woocommerce-checkout&quot;]/div[@class=&quot;woocommerce-NoticeGroup woocommerce-NoticeGroup-checkout&quot;]/ul[@class=&quot;woocommerce-error&quot;]/li[1]/p[@class=&quot;no-button&quot;]</value>
      <webElementGuid>58eaf6e3-2310-42d8-a539-ad0384107b50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-54']/div/div/form[2]/div/ul/li/p</value>
      <webElementGuid>90ebdd92-dea8-4db8-843b-15ae1fc8328e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply coupon'])[1]/following::p[1]</value>
      <webElementGuid>45f941e9-9e28-4f6e-b66d-4cccec79e842</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Billing details'])[1]/preceding::p[1]</value>
      <webElementGuid>0e949fd3-5b7e-4a11-a0aa-8a1cb8fc60c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='is a required field.']/parent::*</value>
      <webElementGuid>39874fe2-06f9-4941-bfe7-48b4cb661e3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/p</value>
      <webElementGuid>ae6529a2-456d-4731-af66-278851ab4567</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Billing Postcode / ZIP is a required field.' or . = 'Billing Postcode / ZIP is a required field.')]</value>
      <webElementGuid>c376a2c6-9b97-468d-94ff-269774b2803a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
